version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
      - MICROSOFT_CLARITY_ID=${MICROSOFT_CLARITY_ID}
    restart: always 